--[[
TALOS
Key Notes
    - DEPARTED CONTENT
    - # BODY OF STONE, HEART OF GOLD, MIND OF REGOLITH
	- Umbra Title: Treacherous Construct
	- Exile Quote: ...and so they remained, unable to break their chains.

Unlock: # NULLREF EXCEPTION

Health: 300 (+90 per level)
Regen: 3.00 (+0.5 per level) HP/S
Damage: 34 (+8.5 per level)
Speed: 10 KM/H
Jump Height: 1 M
Armor: 10 (+1 per level)
Skills:
	- Passive: AURUM
        - # FROM STRENGTH DRAWN FROM LIFEBLOOD RECLAIMED, STRIKES GROW FIERCE. WITH EACH PULSE RENEWED, RHYTHM QUICKENS, EMPOWERING AGILITY. RICHES GAINED FROM EVERY BLOW.
    - Primary: PUGNUS
        - # WITH SWEEPING ARC, FISTS CARVE THROUGH AIR AND FOE. STRIKE FUELS ANOTHER, UNRELENTING. MISS DEMANDS PATIENCE, HALTING.
	- Secondary: VINDICTA
        - # STAND FIRM, FORTRESS AGAINST ONSLAUGHT, ABSORBING BRUNT WITH RESOLVE. IN WAKE OF EACH BLOW TAKEN, STRENGTH AND SWIFTNESS SURGE.
	- Utility: COR
        - # SURGE OF LIFE RADIATES OUTWARD, MENDING WOUNDS AND SHARING VITALITY WITH THOSE NEAR, RESTORING HALF OF WHAT FLOWS WITHIN. IN WAKE, SHIELD OF RESOLVE HARDENS, FORTIFYING.
	- Special: LASERIS
        - # BEAM OF PURE POWER, FURY TEMPERED BY RESTORATION. WITH EACH GAIN, HASTENS.
		- Ancient Scepter: SOLIS
            - # BEAM OF PURE POWER, FURY TEMPERED BY RESTORATION. WITH EACH GAIN, HASTENS. WITH EACH LIFE FORCE CLAIMED, ENDURES.
	
Log:
STONE AND STEEL, BOUND BY PURPOSE, YET HEART SILENTLY YEARNING.

TO KNOW PEACE, TO FEEL KINDNESS IN TOUCH INSTEAD OF BLOW—

HOPE KEPT IN STILLNESS BETWEEN STRIKES.

TO BE SEEN, TO BE LOVED, NOT AS TOOL OF WAR BUT AS SOMETHING MORE.
--]]